---

# Defaults that not suppose to override, just update this when adding new users
all_users:

  root: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvg6CtWc6Q4OcWMHNiaoHsDpuJ5YueMNP58vCz0rQJ4jpFSWWtRTe7GVpof51l7fkxOf7v19Moa0xH2aGPU5YX3IvIWBEhhVYtrCl1eM3LFg86weSyM8/GguvNgnXLGMlM9fkHqXW3m7aElvQ8zpQBMiARccmbwaNpUyxyZFtzKTTWVSeilYLMgkg3++DtkdVZn83IG3CglEVbfPKBpeFNpil+7AE61UEULeuaAaAiNRYmWcriKO2vPwVx/vy2bOm/tYGFQXlc9lCc97KNctUsZxCMRipuq+Gfki39ddmLPFO9YYE/1C6a+0iAGH1qGcpfdKzyRTejPa8VhdORxQWT

  admin: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvg6CtWc6Q4OcWMHNiaoHsDpuJ5YueMNP58vCz0rQJ4jpFSWWtRTe7GVpof51l7fkxOf7v19Moa0xH2aGPU5YX3IvIWBEhhVYtrCl1eM3LFg86weSyM8/GguvNgnXLGMlM9fkHqXW3m7aElvQ8zpQBMiARccmbwaNpUyxyZFtzKTTWVSeilYLMgkg3++DtkdVZn83IG3CglEVbfPKBpeFNpil+7AE61UEULeuaAaAiNRYmWcriKO2vPwVx/vy2bOm/tYGFQXlc9lCc97KNctUsZxCMRipuq+Gfki39ddmLPFO9YYE/1C6a+0iAGH1qGcpfdKzyRTejPa8VhdORxQWT

  zhaozhiyong5: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvg6CtWc6Q4OcWMHNiaoHsDpuJ5YueMNP58vCz0rQJ4jpFSWWtRTe7GVpof51l7fkxOf7v19Moa0xH2aGPU5YX3IvIWBEhhVYtrCl1eM3LFg86weSyM8/GguvNgnXLGMlM9fkHqXW3m7aElvQ8zpQBMiARccmbwaNpUyxyZFtzKTTWVSeilYLMgkg3++DtkdVZn83IG3CglEVbfPKBpeFNpil+7AE61UEULeuaAaAiNRYmWcriKO2vPwVx/vy2bOm/tYGFQXlc9lCc97KNctUsZxCMRipuq+Gfki39ddmLPFO9YYE/1C6a+0iAGH1qGcpfdKzyRTejPa8VhdORxQWT


# Defaults that allow user to override
#
user_group: admin
sudoer_group: wheel
user_admin: admin
home_directory: /export/home
users:
  - zhaozhiyong5
sudoers:
  - zhaozhiyong5
